# Practical Application Lesson 5
## C2C Izaiah LaDuke

In [1]:
import numpy as np
from datascience import *

1) Create an array containing 4 string elements: your first name, your last name, your birth
state and your favorite color.

In [2]:
array=np.array(['Izaiah', 'LaDuke','Wisconsin','Blue'])
array

array(['Izaiah', 'LaDuke', 'Wisconsin', 'Blue'], dtype='<U9')

a. Use a numpy function to make all elements uppercase.

In [3]:
np.char.upper(array)

array(['IZAIAH', 'LADUKE', 'WISCONSIN', 'BLUE'], dtype='<U9')

b. Use a numpy function to count the number of times the letter “a” appears in each
element of your array.

In [4]:
np.char.count(array,'a')

array([2, 1, 0, 0])

c. Optional: Use a numpy function to find the length of each element in the array.
You may need to Google this.

In [5]:
element_length=np.vectorize(len)
element_length(array)

array([6, 6, 9, 4])

2) Create an array containing EVERY OTHER odd number starting with 1 and ending with
(and including) 41.

In [6]:
odd_array=np.arange(1,42,4)
print(odd_array)
odd_array=odd_array.astype(np.float)
print(odd_array)

[ 1  5  9 13 17 21 25 29 33 37 41]
[ 1.  5.  9. 13. 17. 21. 25. 29. 33. 37. 41.]


a. Use numpy to find the sum and the product of the elements of this array. NOTE:
This will require you to convert the elements of your array to floats using the
astype method.

In [7]:
np.sum(odd_array)

231.0

In [8]:
np.prod(odd_array)

7579867420125.0

b. Use numpy to take the natural log of each element.

In [9]:
np.log(odd_array)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

c. Optional: The numpy function np.diff finds the difference between adjacent
elements of an array. Find the SUM of adjacent elements of this array.

In [10]:
adj_sum=[np.sum(odd_array[current: current+2]) for current in np.arange(0, len(odd_array)-1)]
adj_sum

[6.0, 14.0, 22.0, 30.0, 38.0, 46.0, 54.0, 62.0, 70.0, 78.0]